import { bindURL as bindLoginURL } from "./admin/login_url";
import { bindURL as binddashboardURL } from "./admin/dashboard_url";
import { bindURL as bindReportAnalyticsURL } from "./admin/report_master/report_analytics_url";
import { bindURL as bindUploadReportURL } from "./admin/report_master/upload_url";
import { bindURL as bindListReportURL } from "./admin/report_master/list_report_url";
import { bindURL as bindListPressReleaseURL } from "./admin/report_master/list_pr_url";
import { bindURL as bindListCompanyURL } from "./admin/report_master/list_company_url";
import { bindURL as bindListSegmentURL } from "./admin/report_master/list_segment_url";
import { bindURL as bindListSegmentGraphURL } from "./admin/report_master/list_segment_graph_url";
import { bindURL as bindListSnapshotURL } from "./admin/report_master/list_snapshot_url";
import { bindURL as bindListBarGraphURL } from "./admin/report_master/bar_graph_url";
import { bindURL as bindListFAQsURL } from "./admin/report_master/list_faqs_url";
import { bindURL as bindListKeywordURL } from "./admin/report_master/list_keyword_url";
import { bindURL as bindCategoryMasterURL } from "./admin/report_master/category_master_url";
import { bindURL as bindRegionMasterURL } from "./admin/report_master/region_master_url";
import { bindURL as bindProductBannerURL } from "./admin/report_master/product_banner_url";
import { bindURL as bindSitemapURL} from "./admin/report_master/sitemap_url";
import { bindURL as bindDatabaseReportURL } from "./admin/report_master/database_url";

import { bindURL as bindPartnerURL} from "./admin/sales_master/partner_url";
import { bindURL as bindMembersURL } from "./admin/sales_master/members_url";
import { bindURL as bindOurClientURL } from "./admin/sales_master/our_client_url"
import { bindURL as bindTestimonialURL } from "./admin/sales_master/testimonial_url";
import { bindURL as bindQuotationURL } from "./admin/sales_master/quotation_url";
import { bindURL as bindEmailTemplateURL } from "./admin/sales_master/email_template_url";
import { bindURL as bindReportPromotionURL } from "./admin/sales_master/report_promotion_url";
import { bindURL as bindSalesTrackingURL } from "./admin/sales_master/sales_tracking_url";
import { bindURL as bindLeadMasterURL } from "./admin/sales_master/lead_master_url";
import { bindURL as bindSubscriberURL } from "./admin/sales_master/subscriber_url";
import { bindURL as bindDiscountCouponURL } from "./admin/sales_master/subscriber_url";
import { bindURL as bindEmailToSubscriberURL } from "./admin/sales_master/subscriber_url";
import { bindURL as bindPromotionalEmailURL } from "./admin/sales_master/subscriber_url";
import { bindURL as bindEmailProviderURL } from "./admin/sales_master/subscriber_url";
import { bindURL as bindUploadSalesURL } from "./admin/sales_master/subscriber_url";
import { bindURL as bindDatabaseSalesURL } from "./admin/sales_master/subscriber_url";


bindLoginURL();
binddashboardURL();
bindReportAnalyticsURL();
bindUploadReportURL();
bindListReportURL();
bindListPressReleaseURL();
bindListCompanyURL();
bindListSegmentURL();
bindListSegmentGraphURL();
bindListSnapshotURL();
bindListBarGraphURL();
bindListFAQsURL();
bindListKeywordURL();
bindCategoryMasterURL();
bindRegionMasterURL();
bindProductBannerURL();
bindSitemapURL();
bindDatabaseReportURL();

bindPartnerURL();
bindMembersURL();
bindOurClientURL();
bindTestimonialURL();
bindQuotationURL();
bindEmailTemplateURL();
bindReportPromotionURL();
bindSalesTrackingURL();
bindLeadMasterURL();
bindSubscriberURL();
bindDiscountCouponURL();
bindEmailToSubscriberURL();
bindPromotionalEmailURL();
bindEmailProviderURL();
bindUploadSalesURL();
bindDatabaseSalesURL();